INHERIT: "active-handout.yml"

site_name: "Computação Gráfica"
site_author: "Luciano Pereira Soares"

extra:
    materia: Computação Gráfica
    professor: Luciano Pereira Soares
    semestre: 2023/1
    url_acompanhamentos: http://localhost:8081
    id_curso: 10


nav:
    - Home: index.md

    - Aulas:
        - "01 - Introdução": aulas/01-introducao/index.md
        - "02 - Desenhando Triângulos e X3D": aulas/02-desenhando_triangulos_e_X3D/index.md

    - Projetos:
        - "Projeto 1.1": projetos/projeto11.md

