INHERIT: "active-handout.yml"

site_name: "Computação Gráfica"
site_author: "Luciano Pereira Soares"

extra:
    materia: Computação Gráfica
    professor: Luciano Pereira Soares
    semestre: 2023/1
    url_acompanhamentos: http://localhost:8081
    id_curso: 10


nav:
    - Home: index.md

    - Aulas:
        - "01 - Introdução": aulas/01-introducao/index.md
        - "02 - Desenhando Triângulos e X3D": aulas/02-desenhando_triangulos_e_X3D/index.md
        - "03 - Renderização e Transformações Geométricas": aulas/03-renderizacao_transformacoes/index.md
        - "04 - Coordenadas Homogêneas e Quatérnios": aulas/04-coordenadas_homogeneas_e_quaternios/index.md
        - "05 - Sistemas de Coordenadas": aulas/05-sistemas_de_coordenadas/index.md
        - "06 - Projeções": aulas/06-projecoes/index.md
        - "07 - Revisão 1": aulas/07-revisao1/index.md
        - "08 - Grafo de Cena": aulas/08-malhas_e_grafo_de_cena/index.md
        - "09 - Interpolação em Triângulos": aulas/09-interpolacao_em_triangulos/index.md
        - "10 - Anti-aliasing e Visibilidade": aulas/10-aliasing_e_visibilidade/index.md
        - "11 - Mapeamento": aulas/11-mapeamento_de_texturas/index.md
        - "12 - Revisão 2": aulas/12-revisao2/index.md
        - "13 - Revisão 3": aulas/13-revisao3/index.md
        - "14 - Primitivas Geométricas": aulas/14-primitivas_geometricas/index.md
        - "15 - Iluminação": aulas/15-iluminacao/index.md
        #- "16 - Curvas e Animações": aulas/15-curvas_e_animacoes/index.md
        #- "17 - Coordenadas Esféricas e Pipeline de Renderização": aulas/17-coord_esfericas_e_pipeline/index.md
        #- "18 - Supersampling": aulas/18-supersampling/index.md

    - Projetos:
        - "Projeto 1.1": projetos/projeto11.md
        - "Projeto 1.2": projetos/projeto12.md
        - "Projeto 1.3": projetos/projeto13.md
        - "Projeto 1.4": projetos/projeto14.md
        - "Projeto 1.5": projetos/projeto15.md
        #- "Projeto 1.5": projetos/projeto16.md

    - Exemplos X3D: https://lpsoares.github.io/Renderizador/index.html
