INHERIT: "active-handout.yml"

site_name: "Computação Gráfica"
site_author: "Luciano Pereira Soares"

extra:
    materia: Computação Gráfica
    professor: Luciano Pereira Soares
    semestre: 2023/1
    url_acompanhamentos: http://localhost:8081
    id_curso: 10


nav:
    - Home: index.md

    - Aulas:
        - "01 - Introdução": aulas/01-introducao/index.md
        - "02 - Desenhando Triângulos e X3D": aulas/02-desenhando_triangulos_e_X3D/index.md
        - "03 - Renderização e Transformações Geométricas": aulas/03-renderizacao_transformacoes/index.md
        - "04 - Coordenadas Homogêneas e Quatérnios": aulas/04-coordenadas_homogeneas_e_quaternios/index.md
        - "05 - Sistemas de Coordenadas": aulas/05-sistemas_de_coordenadas/index.md
        - "06 - Projeções": aulas/06-projecoes/index.md
        - "07 - Revisão 1": aulas/07-revisao1/index.md
        #- "08 - Grafo de Cena": aulas/08-grafo_de_cena/index.md
        #- "09 - Interpolação em Triângulos": aulas/09-interpolacao_em_triangulos/index.md
        #- "10 - Mapeamento": aulas/10-mapeamento/index.md
        #- "11 - Iluminação": aulas/11-iluminacao/index.md
        #- "12 - Curvas e Animações": aulas/12-curvas_e_animacoes/index.md
        #- "13 - Revisão 2": aulas/13-revisao2/index.md
        #- "14 - Coordenadas Esféricas e Pipeline de Renderização": aulas/14-coord_esfericas_e_pipeline/index.md
        #- "15 - Supersampling": aulas/15-supersampling/index.md

    - Projetos:
        - "Projeto 1.1": projetos/projeto11.md
        - "Projeto 1.2": projetos/projeto12.md
        #- "Projeto 1.3": projetos/projeto13.md

