site_name: "Computação Gráfica"
site_author: "Luciano Soares & Fabio Orfali"

docs_dir: docs
site_dir: site

site_url: https://lpsoares.github.io/ComputacaoGrafica/
repo_url: https://github.com/lpsoares/ComputacaoGrafica
repo_name: lpsoares/ComputacaoGrafica
edit_uri: edit/main/content/
dev_addr: 127.0.0.1:8000

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

plugins:
  - search:
      lang: pt
  - mkdocs-jupyter:
      execute: false      # true/auto para executar notebooks no build
      include_source: true
      ignore_h1_titles: true
      allow_errors: false
      kernel_name: python3
      show_input: true
      include_requirejs: true
  - macros
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      locale: pt_BR

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  materia: Computação Gráfica
  professor: Luciano Soares & Fabio Orfali
  professor Auxiliar: Gustavo Braga
  semestre: 2026/2
  url_acompanhamentos: http://localhost:8081
  id_curso: 10
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lpsoares

hooks:
  - hooks.py

watch:
  - docs
  - mkdocs.yml

nav:
    - Home: index.md

    - Aulas:
        - "01 - Introdução": aulas/01-introducao/index.md
        - "02 - Desenhando Triângulos": aulas/02-desenhando_triangulos/index.md
        - "03 - Renderização e Transformações Geométricas": aulas/03-renderizacao_transformacoes/index.md
    #     - "04 - Coordenadas Homogêneas e Quatérnios": aulas/04-coordenadas_homogeneas_e_quaternios/index.md
    #     - "05 - Sistemas de Coordenadas": aulas/05-sistemas_de_coordenadas/index.md
    #     - "06 - Projeções Perspectiva": aulas/06-projecoes_perspectiva/index.md
    #     - "07 - Malhas e Grafo de Cena": aulas/07-malhas_e_grafo_de_cena/index.md
    #     - "08 - Interpolação em Triângulos": aulas/08-interpolacao_em_triangulos/index.md
    #     - "09 - Mapeamento de Texturas": aulas/09-mapeamento_de_texturas/index.md
    #     - "10 - Anti-aliasing e Visibilidade": aulas/10-aliasing_e_visibilidade/index.md
    #     - "11 - Materiais e Iluminação": aulas/11-materiais_e_iluminacao/index.md
    #     - "12 - Curvas e Animações": aulas/12-curvas_e_animacoes/index.md
    #     - "13 - Pipeline Gráfico": aulas/13-pipeline_grafico/index.md
    #     - "14 - Shaders": aulas/14-shaders/index.md
    #     - "15 - Aleatoriedade e Ruídos": aulas/15-aleatoriedade_e_ruidos/index.md
    #     - "16 - Ray Tracing 1": aulas/16-ray_tracing/index.md
    #     - "17 - Ray Tracing 2": aulas/17-ray_tracing2/index.md
    #     - "18 - Ray Marching 1": aulas/18-ray_marching/index.md
    #     - "19 - Ray Marching 2": aulas/19-ray_marching2/index.md

    # - Revisões:
    #     - "Transformações e Projeções": revisoes/01-revisao_transformacoes_e_projecoes/index.md
    #     - "Malhas e Grafo de Cena": revisoes/02-revisao_malhas_grafodecena/index.md
    #     - "Interpolação, Visibilidade e Mipmaps": revisoes/03-revisao_interpolacao_mipmap_visibilidade/index.md
    #     - "Iluminação e Animação": revisoes/04-revisao_iluminacao_animacao/index.md

    # - Extra:
    #     - "Filtragem em Mapeamento de Texturas": extra/filtragem_em_mapeamento_de_texturas/index.md
    #     - "Primitivas Geométricas": extra/primitivas_geometricas/index.md

    - Projetos:
        - "Projeto 1.1": projetos/projeto11.md
    #     - "Projeto 1.2": projetos/projeto12.md
    #     - "Projeto 1.3": projetos/projeto13.md
    #     - "Projeto 1.4": projetos/projeto14.md
    #     - "Projeto 1.5": projetos/projeto15.md
    #     - "Projeto 2": projetos/projeto2.md
    #     - "Projeto 3": projetos/projeto3.md

    - Edições Passadas:

      - 2025:
        - "01 - Introdução": edicoes/2025/01-introducao/index.md
        - "02 - Desenhando Triângulos": edicoes/2025/02-desenhando_triangulos/index.md
        - "03 - Renderização e Transformações Geométricas": edicoes/2025/03-renderizacao_transformacoes/index.md
        - "04 - Coordenadas Homogêneas e Quatérnios": edicoes/2025/04-coordenadas_homogeneas_e_quaternios/index.md
        - "05 - Sistemas de Coordenadas": edicoes/2025/05-sistemas_de_coordenadas/index.md
        - "06 - Projeções Perspectiva": edicoes/2025/06-projecoes_perspectiva/index.md
        - "07 - Malhas e Grafo de Cena": edicoes/2025/07-malhas_e_grafo_de_cena/index.md
        - "08 - Interpolação em Triângulos": edicoes/2025/08-interpolacao_em_triangulos/index.md
        - "09 - Mapeamento de Texturas": edicoes/2025/09-mapeamento_de_texturas/index.md
        - "10 - Anti-aliasing e Visibilidade": edicoes/2025/10-aliasing_e_visibilidade/index.md
        - "11 - Materiais e Iluminação": edicoes/2025/11-materiais_e_iluminacao/index.md
        - "12 - Curvas e Animações": edicoes/2025/12-curvas_e_animacoes/index.md
        - "13 - Pipeline Gráfico": edicoes/2025/13-pipeline_grafico/index.md
        - "14 - Shaders": edicoes/2025/14-shaders/index.md
        - "15 - Aleatoriedade e Ruídos": edicoes/2025/15-aleatoriedade_e_ruidos/index.md
        - "16 - Ray Tracing 1": edicoes/2025/16-ray_tracing/index.md
        - "17 - Ray Tracing 2": edicoes/2025/17-ray_tracing2/index.md
        - "18 - Ray Marching 1": edicoes/2025/18-ray_marching/index.md
        - "19 - Ray Marching 2": edicoes/2025/19-ray_marching2/index.md

      - 2024:
        - "01 - Introdução": edicoes/2024/01-introducao/index.md
        - "02 - Desenhando Triângulos": edicoes/2024/02-desenhando_triangulos/index.md
        - "03 - Renderização e Transformações Geométricas": edicoes/2024/03-renderizacao_transformacoes/index.md
        - "04 - Coordenadas Homogêneas e Quatérnios": edicoes/2024/04-coordenadas_homogeneas_e_quaternios/index.md
        - "05 - Sistemas de Coordenadas": edicoes/2024/05-sistemas_de_coordenadas/index.md
        - "06 - Projeções Perspectiva": edicoes/2024/06-projecoes_perspectiva/index.md
        - "07 - Revisão 1": edicoes/2024/07-revisao1/index.md
        - "08 - Malhas e Grafo de Cena": edicoes/2024/08-malhas_e_grafo_de_cena/index.md
        - "08x - Revisão 2": edicoes/2024/08x-revisao2_malhas_grafoCena/index.md
        - "09 - Interpolação em Triângulos": edicoes/2024/09-interpolacao_em_triangulos/index.md
        - "10 - Mapeamento": edicoes/2024/10-mapeamento_de_texturas/index.md
        - "11 - Anti-aliasing e Visibilidade": edicoes/2024/11-aliasing_e_visibilidade/index.md
        - "12 - Revisão 3": edicoes/2024/12-revisao3_interpolacao_mipmap_visibilidade/index.md
        - "13 - Primitivas Geométricas": edicoes/2024/13-primitivas_geometricas/index.md
        - "14 - Materiais e Iluminação": edicoes/2024/14-materiais_e_iluminacao/index.md
        - "15 - Curvas e Animações": edicoes/2024/15-curvas_e_animacoes/index.md
        - "16 - Revisão 4": edicoes/2024/16-revisao4/index.md
        - "17 - Pipeline Gráfico": edicoes/2024/17-pipeline_grafico/index.md
        - "18 - Shaders": edicoes/2024/18-shaders/index.md
        - "19 - Aleatoriedade e Ruídos": edicoes/2024/19-aleatoriedade_e_ruidos/index.md
        - "20 - Ray Tracing 1": edicoes/2024/20-ray_tracing/index.md
        - "21 - Ray Tracing 2": edicoes/2024/21-ray_tracing2/index.md
        - "22 - Ray Marching 1": edicoes/2024/22-ray_marching/index.md
        - "23 - Ray Marching 2": edicoes/2024/23-ray_marching2/index.md

    - Especificação X3D: https://www.web3d.org/specifications/X3Dv4/ISO-IEC19775-1v4-IS/
    
    - Exemplos X3D: https://lpsoares.github.io/Renderizador/index.html
