INHERIT: "active-handout.yml"

site_name: "Computação Gráfica"
site_author: "Luciano Pereira Soares"

extra:
    materia: Computação Gráfica
    professor: Luciano Pereira Soares
    semestre: 2023/1
    url_acompanhamentos: http://localhost:8081
    id_curso: 10


nav:
    - Home: index.md

    - Aulas:
        - "01 - Introdução": aulas/01-introducao/index.md
        - "02 - Desenhando Triângulos e X3D": aulas/02-desenhando_triangulos_e_X3D/index.md
        - "03 - Renderização e Transformações Geométricas": aulas/03-renderizacao_transformacoes/index.md
        #- "04 - Coordenadas Homogêneas e Quatérnions": aulas/04-coordenadas_homogeneas_e_quaternions/index.md

    - Projetos:
        - "Projeto 1.1": projetos/projeto11.md
        #- "Projeto 1.2": projetos/projeto12.md
        #- "Projeto 1.3": projetos/projeto13.md

